### PR TITLE
Add full typing support to the library.

### LINKED ISSUE #84: Add a py.typed marker file
Drain3 is annotated with type metadata, but does not include the [`py.typed` marker file required by PEP 561](https://peps.python.org/pep-0561/#packaging-type-information). As a result, e.g. MyPy refuses to consider the annotations in the Drain3 source when typechecking dependent programs. Please include the marker file in future releases.

### PR DESCRIPTION
**Pull request by no-preserve-root**
At the moment, Drain3 has incomplete and/or missing types on some classes and functions. This PR adds full typing everywhere (so `mypy --strict` passes) and adds the missing `py.typed` marker file. There are some changes to the codebase (reassignments that change type, missing abstract methods) that should not change semantics, plus one bugfix.

Changes in details:
 - MyPy and available type stubs added to dev dependencies.
 - Type annotations are used everywhere. Abstract types (Mapping etc.) are preferred. The library passes mypy --strict tests.
 - Minor logic changes and new asserts to support typing.
 - Introduction of abstract methods in DrainBase.
 - 'parameter_extraction_cache_capacity' is now correctly parsed as an int.
 - py.typed marker added (fixes #84).

### CODE REVIEW

**Comment by Superskyyy** [comment]
Thank you for the contribution! I will review it this weekend.

**Comment by wiperpaul** [comment]
@Superskyyy can this PR be resurrected.

**Comment by Superskyyy** [comment]
> @Superskyyy can this PR be resurrected.

Yes, I have reviewed the changes, LGTM. A new version will be released to pypi once I verify things are working fine. Very sorry for the delay. @no-preserve-root @wiperpaul thanks for the contribution!

**Review by Superskyyy — COMMENTED** [review]
LGTM

**Pull request merged**
